# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Audiogid.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_aubook(object):
    def setupUi(self, Window_aubook):
        Window_aubook.setObjectName("Window_aubook")
        Window_aubook.setFixedSize(900, 600)
        self.centralwidget = QtWidgets.QWidget(Window_aubook)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(325, 200, 250, 23))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255, 190);")
        self.pushButton.setObjectName("pushButton")
        Window_aubook.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_aubook)
        QtCore.QMetaObject.connectSlotsByName(Window_aubook)

    def retranslateUi(self, Window_aubook):
        _translate = QtCore.QCoreApplication.translate
        Window_aubook.setWindowTitle(_translate("Window_aubook", "Возрождение - Арктика - аудиогид"))
        self.pushButton.setText(_translate("Window_aubook", "Аудиогид"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_aubook = QtWidgets.QMainWindow()
    ui = Ui_Window_aubook()
    ui.setupUi(Window_aubook)
    Window_aubook.show()
    sys.exit(app.exec_())
