# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baza.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_revival(object):
    def setupUi(self, Window_revival):
        Window_revival.setObjectName("Window_revival")
        Window_revival.setFixedSize(900, 600)
        self.centralwidget = QtWidgets.QWidget(Window_revival)
        self.centralwidget.setStyleSheet("QWidget::pane\n"
"{\n"
"    border: 1px;\n"
"    background: rgb(0, 0, 0, 0);\n"
"}\n"
"\n"
"QTabBar::tab\n"
"{\n"
"    background: rgb(25, 128, 139);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    background: rgb(45, 69, 93)\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.Masha = QtWidgets.QLabel(self.centralwidget)
        self.Masha.setGeometry(QtCore.QRect(300, 20, 281, 250))
        self.Masha.setText("")
        self.Masha.setPixmap(QtGui.QPixmap("./лого2.png"))
        self.Masha.setObjectName("Masha")
        self.b_turBaz = QtWidgets.QPushButton(self.centralwidget)
        self.b_turBaz.setGeometry(QtCore.QRect(220, 350, 450, 23))
        self.b_turBaz.setStyleSheet("background-color: rgb(149, 200, 242, 190);\n"
"border: 1px solid; \n"
"border-color: rgb(255, 255, 255);")
        self.b_turBaz.setObjectName("b_turBaz")
        self.b_turMar = QtWidgets.QPushButton(self.centralwidget)
        self.b_turMar.setGeometry(QtCore.QRect(220, 300, 450, 23))
        self.b_turMar.setStyleSheet("background-color: rgb(149, 200, 242, 190);\n"
"border: 1px solid; \n"
"border-color: rgb(255, 255, 255);")
        self.b_turMar.setObjectName("b_turMar")
        self.b_aubook = QtWidgets.QPushButton(self.centralwidget)
        self.b_aubook.setGeometry(QtCore.QRect(220, 400, 450, 23))
        self.b_aubook.setStyleSheet("background-color: rgb(149, 200, 242, 190);\n"
"border: 1px solid; \n"
"border-color: rgb(255, 255, 255);")
        self.b_aubook.setObjectName("b_aubook")
        self.b_oNax = QtWidgets.QPushButton(self.centralwidget)
        self.b_oNax.setGeometry(QtCore.QRect(220, 450, 450, 23))
        self.b_oNax.setStyleSheet("background-color: rgb(149, 200, 242, 190);\n"
"border: 1px solid; \n"
"border-color: rgb(255, 255, 255);")
        self.b_oNax.setObjectName("b_oNax")
        self.b_fond = QtWidgets.QPushButton(self.centralwidget)
        self.b_fond.setGeometry(QtCore.QRect(220, 500, 450, 23))
        self.b_fond.setStyleSheet("background-color: rgb(149, 200, 242, 190);\n"
"border: 1px solid; \n"
"border-color: rgb(255, 255, 255);")
        self.b_fond.setObjectName("b_fond")
        Window_revival.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_revival)
        QtCore.QMetaObject.connectSlotsByName(Window_revival)

    def retranslateUi(self, Window_revival):
        _translate = QtCore.QCoreApplication.translate
        Window_revival.setWindowTitle(_translate("Window_revival", "Возрождение"))
        self.b_turBaz.setText(_translate("Window_revival", "Туристическая база"))
        self.b_turMar.setText(_translate("Window_revival", "Туристический маршрут"))
        self.b_aubook.setText(_translate("Window_revival", "Арктика - Аудиогид"))
        self.b_oNax.setText(_translate("Window_revival", "О нас"))
        self.b_fond.setText(_translate("Window_revival", "Фонд поддержки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_revival = QtWidgets.QMainWindow()
    ui = Ui_Window_revival()
    ui.setupUi(Window_revival)
    Window_revival.show()
    sys.exit(app.exec_())
