# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'found.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_found(object):
    def setupUi(self, Window_found):
        Window_found.setObjectName("Window_found")
        Window_found.setFixedSize(900, 600)
        self.centralwidget = QtWidgets.QWidget(Window_found)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 880, 300))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"\n"
"border: 1px;\n"
"border-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 130, 211, 201))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../application/clear.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 130, 211, 201))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../application/арктика.png"))
        self.label_2.setObjectName("label_2")
        self.b_clear = QtWidgets.QPushButton(self.centralwidget)
        self.b_clear.setGeometry(QtCore.QRect(65, 350, 181, 23))
        self.b_clear.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.b_clear.setObjectName("b_clear")
        self.b_arct = QtWidgets.QPushButton(self.centralwidget)
        self.b_arct.setGeometry(QtCore.QRect(320, 350, 181, 23))
        self.b_arct.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.b_arct.setObjectName("b_arct")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 380, 261, 201))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../application/лого2_photo-resizer.ru.png"))
        self.label_3.setObjectName("label_3")
        self.b_v = QtWidgets.QPushButton(self.centralwidget)
        self.b_v.setGeometry(QtCore.QRect(320, 410, 181, 141))
        self.b_v.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.b_v.setObjectName("b_v")
        Window_found.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_found)
        QtCore.QMetaObject.connectSlotsByName(Window_found)

    def retranslateUi(self, Window_found):
        _translate = QtCore.QCoreApplication.translate
        Window_found.setWindowTitle(_translate("Window_found", "Возрождение - Фонд поддержки"))
        self.textBrowser.setHtml(_translate("Window_found", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">Половина нашего дохода будет направлена в благотворительные фонды Арктики для улучшения экологии природной зоны, в том числе помощи вымирающим видам</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">Здесь представлены ссылки на такие организации:</span></p></body></html>"))
        self.b_clear.setText(_translate("Window_found", "Чистая Арктика"))
        self.b_arct.setText(_translate("Window_found", "Ресурсный центр \"Арктика\""))
        self.b_v.setText(_translate("Window_found", "Поддержать наш проект"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_found = QtWidgets.QMainWindow()
    ui = Ui_Window_found()
    ui.setupUi(Window_found)
    Window_found.show()
    sys.exit(app.exec_())
