# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Turistichescay_marshrut.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_turMar(object):
    def setupUi(self, Window_turMar):
        Window_turMar.setObjectName("Window_turMar")
        Window_turMar.setFixedSize(900, 600)
        self.centralwidget = QtWidgets.QWidget(Window_turMar)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 190, 391, 161))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"\n"
"border: 1px;\n"
"border-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(490, 320, 391, 161))
        self.textBrowser_2.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"\n"
"border: 1px;\n"
"border-color: rgb(255, 255, 255);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        Window_turMar.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_turMar)
        QtCore.QMetaObject.connectSlotsByName(Window_turMar)

    def retranslateUi(self, Window_turMar):
        _translate = QtCore.QCoreApplication.translate
        Window_turMar.setWindowTitle(_translate("Window_turMar", "Возрождение - Туристический маршрут"))
        self.textBrowser.setHtml(_translate("Window_turMar", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">Чтобы добраться от Якутска до Нордвика необходимо преодолеть немалое расстояние, поэтому мы разработали особый туристический маршрут, который просходит по реке Лене и основан на историческом пути Братьев Лаптевых, которые первыми исследовали эти холодные и суровые земли.</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Window_turMar", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">На маршруте вы сможете увидеть своими глазами уникальную природу нашей страны и погрузиться в историю, благодаря экскурсоводам и тематическим мероприятиям, проходящим на борту корабля.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_turMar = QtWidgets.QMainWindow()
    ui = Ui_Window_turMar()
    ui.setupUi(Window_turMar)
    Window_turMar.show()
    sys.exit(app.exec_())
