# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Turistichescay_baza.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_turBaz(object):
    def setupUi(self, Window_turBaz):
        Window_turBaz.setObjectName("Window_turBaz")
        Window_turBaz.setFixedSize(900, 600)
        self.centralwidget = QtWidgets.QWidget(Window_turBaz)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 160, 901, 291))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 0, 0, 100);\n"
"\n"
"border: 1px;\n"
"border-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        Window_turBaz.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window_turBaz)
        QtCore.QMetaObject.connectSlotsByName(Window_turBaz)

    def retranslateUi(self, Window_turBaz):
        _translate = QtCore.QCoreApplication.translate
        Window_turBaz.setWindowTitle(_translate("Window_turBaz", "Возрождение - Туристическая база"))
        self.textBrowser.setHtml(_translate("Window_turBaz", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">Лучшее место, чтобы остановиться после плавания на корабле - турбаза! Турбаза, расположенная в Нордвике, состоит из административного здания, небольшого этнографического музея при административном здании и два вида домов - обычных небольших домиков для людей, которые хотят попробовать развлечения, но проживать с полным набором их обычного образа жизни или же полностью погрузиться в жизнь местных народов, таких как энцы, нганасаны, долганы, ненцы, эвенки и пожить в их традиционных жилищах - чумах. Стоит отметить, что время проживания в турбазе ограниченно лишь вашим желанием.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">Место для турбазы выбрано не случайно. Останки старого поселка помогут сэконимить на инфраструктуре, фундаментах и в строительстве большинства зданий. Электричеством туристическую базу могут обеспечивать две электростанции находящиеся рядом.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">Остановившись в этом посёлке вы можете полностью ощутить себя жителем холодных земель: носить традиционную народную одежду, попробовать национальные блюда, покататься на оленях и собачьх упряжках, а так же возможно, увидеть северное сияние! Такая турбаза понравится как любителям культуры народов и семейным группам, так и поклонникам экстремальных условий.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_turBaz = QtWidgets.QMainWindow()
    ui = Ui_Window_turBaz()
    ui.setupUi(Window_turBaz)
    Window_turBaz.show()
    sys.exit(app.exec_())
